"""Regenerate the cross-language v2 golden fixture from the Python gateway implementation.

    apps/edge-gateway/.venv/bin/python scripts/generate-v2-golden.py

The fixture is deterministic (fixed IDs, timestamps and test-only keys) and is verified by
both `apps/edge-gateway/tests/test_v2.py` and `tests/intake-v2.test.ts`. Regenerate it only
when the contract changes on purpose.
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps" / "edge-gateway"))
from gateway.v2 import signature, validate_envelope

DEVICE_KEY = "golden-device-key-00000000000000000000000000"
REVIEWER_KEY = "golden-reviewer-key-0000000000000000000000000"
BLOCKS = [
    ("p1_line_0", 1, [40, 30, 300, 14], "Synthetic inspection report"),
    ("p1_line_1", 1, [40, 60, 300, 14], "Contact: [TOKEN_0123456789abcdef01234567]"),
    ("p1_line_2", 1, [40, 90, 300, 14], "Year built: 2016"),
    ("p1_line_3", 1, [40, 120, 300, 14], "Construction: masonry noncombustible"),
    ("p1_line_4", 1, [40, 150, 300, 14], "Primary risk state: PA"),
    ("p2_line_0", 2, None, "TIV: 72,000,000 USD \u2014 caf\u00e9 annex included"),
]
artifacts = [{"id": i, "mediaType": "text/plain", "text": t} for i, _, _, t in BLOCKS]
descriptors = [
    {"id": i, "mediaType": "text/plain", "byteLength": len(t.encode()), "sha256": hashlib.sha256(t.encode()).hexdigest(), "page": p, "blockId": i, "box": b}
    for i, p, b, t in BLOCKS
]
manifest = {
    "version": 2,
    "intakeId": "11111111-1111-4111-8111-111111111111",
    "documentId": "22222222-2222-4222-8222-222222222222",
    "revision": 3,
    "deviceId": "rdk-x5-golden",
    "tenantId": "tenant-golden",
    "caseId": None,
    "policyVersion": "privacy-v2-text-only",
    "createdAt": "2026-09-19T12:00:00.000Z",
    "classification": {
        "status": "CLASSIFIED",
        "documentType": "inspection_report",
        "confidence": 0.912345,
        "calibration": "UNCALIBRATED",
        "alternatives": [{"label": "inspection_report", "confidence": 0.912345}, {"label": "mixed", "confidence": 0.05}, {"label": "correspondence", "confidence": 1e-7}],
        "attributes": {"language": "en", "pageCount": 2, "hasTables": False, "lineOfBusiness": "property"},
        "modelId": "local-text-v1",
        "artifactDigest": "ab" * 32,
        "runtimeVersion": "multinomial-v1",
        "latencyMs": 12.5,
        "evidenceIds": ["p1_line_0", "p1_line_2"],
    },
    "matchHints": {"documentType": "inspection_report", "riskState": "PA", "lineOfBusiness": "property", "yearRange": [2010, 2019], "tivBucket": "10m_100m"},
    "quality": {"status": "REVIEW", "reasons": ["PERSPECTIVE_UNCERTAIN", "UNCALIBRATED_POLICY"], "policyVersion": "quality-v2-provisional", "pageCount": 2},
    "fields": [{"path": "field_0.person_name", "classification": "tokenized", "method": "deterministic-pattern-v1", "confidence": 0.99}],
    "artifacts": descriptors,
    "destinations": ["lloyd-api", "gemini"],
    "approval": {"reviewerId": "reviewer-golden", "approvedAt": "2026-09-19T12:05:00.000Z", "expiresAt": "2026-09-19T12:15:00.000Z", "acknowledgedQuality": True},
}
envelope = {
    "manifest": manifest,
    "artifacts": artifacts,
    "authentication": {
        "keyId": "golden-key-1",
        "algorithm": "HMAC-SHA256",
        "signature": signature(manifest, DEVICE_KEY),
        "reviewerSignature": signature(manifest, REVIEWER_KEY, "reviewer"),
    },
}
validate_envelope(envelope)
fixture = {
    "description": "Cross-language v2 golden fixture generated by the Python gateway. Keys are test-only.",
    "now": "2026-09-19T12:06:00.000Z",
    "policy": {
        "devices": {"golden-key-1": {"tenantId": "tenant-golden", "deviceId": "rdk-x5-golden", "key": DEVICE_KEY}},
        "reviewers": {"reviewer-golden": {"tenantId": "tenant-golden", "key": REVIEWER_KEY, "caseIds": ["*"]}},
        "destinations": ["lloyd-api", "gemini", "gptzero", "elasticsearch"],
    },
    "envelope": envelope,
}
target = ROOT / "packages" / "contracts" / "fixtures" / "intake-v2.golden.json"
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(json.dumps(fixture, indent=2, ensure_ascii=False) + "\n")
print(target, envelope["authentication"]["signature"])
